# Generated by Django 5.2.3 on 2025-07-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_coursepayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
