# Generated by Django 5.2.3 on 2025-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("remittance", "Remittance")],
                default="remittance",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=120, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=120,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
