# Generated by Django 5.2.3 on 2025-06-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_course_lesson_alter_lesson_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="lesson",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.course",
                verbose_name="Урок",
            ),
        ),
    ]
