# Generated by Django 5.2.3 on 2025-07-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_coursepayment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoursePayment",
        ),
    ]
