# Generated by Django 5.2.3 on 2025-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(),
        ),
    ]
