# Generated by Django 5.2.3 on 2025-07-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0010_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
    ]
