name: Django CI

on: [ push, pull_request ]

env:
  SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install Poetry

      - name: Install flake8
        run: poetry add --group dev flake8

      - name: Run flake8
        run: poetry run flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run tests
        run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my_app:${{ github.sha }} .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my_app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} #

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Deploy to server
        run: |
            ssh -tt -o StrictHostKeyChecking=no \
                ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            sudo usermod -aG docker $USER
            newgrp docker
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my_app:${{ github.sha }}
            docker stop myapp || true
            docker rm myapp || true
            docker run -d \
                --name myapp \
                -p 80:8000 \
                -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
                ${{ secrets.DOCKER_HUB_USERNAME }}/my_app:${{ github.sha }}
            EOF
